### ISSUE TITLE
No Internet Connection Issue

### ISSUE THREAD

**Issue by njamal816** [LIMECAKE/MATH-OCR#1]
Hello,

Thank you for this. However, after building the app and running, it shows no internet connection. Can you please check on this?

**Comment by AzelyFox** [comment]
@njamal816 Hi, you should get MathPix OCR Api keys, and edit ocr/mathpix/Constant.java values to work ;)

**Comment by njamal816** [comment]
Thank you for your quick reply. Sure. I will be doing. Thanks once again.
